POST http://localhost:3000/vendedor/agregarVendedor HTTP/1.1
Content-Type: application/json

{
    "id_Vendedor":223272,
    "nombre_vendedor":"Kato",
    "numeroTel_vendedor":123
}

###
DELETE http://localhost:3000/vendedor/eliminarVendedor HTTP/1.1
Content-Type: application/json

{
    "id_Vendedor":223272
}