POST http://localhost:3000/producto/agregarproducto HTTP/1.1
Content-Type: application/json

{
    "id_producto":223272,
    "nombre":"Kato"
}

###
DELETE http://localhost:3000/producto/eliminarproducto HTTP/1.1
Content-Type: application/json

{
    "id_producto":223272
}